# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-18.04"

	#Access to TFE
	config.vm.network "forwarded_port", guest: 80, host: 80
	config.vm.network "forwarded_port", guest: 443, host: 443
	config.vm.network "forwarded_port", guest: 8800, host: 8800

	config.vm.provider "virtualbox" do |vb, override|
	    # TFE Requirements
	    vb.memory = 4096
	    vb.cpus = 2
	 end

	config.vm.provider "vmware_desktop" do |vb, override|
	    # TFE Requirements
	    vb.vmx["memsize"] = "4096"
	    vb.vmx["numvcpus"] = "2"
	end

	#Install Terraform Enterprise
	config.vm.provision "shell", run: "once", inline: <<-SHELL
	  apt-get update
	  # TFE prereqs the installer does this
	  # sudo apt-get install -y libjs-jquery
	  # Allows Grub update to continue noninteractive
	  # DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
	SHELL
      end
